const nav = document.getElementById('nav-menu');
const menuToggle = document.querySelector('.menu-toggle');
const navbar = document.getElementById('navbar');
menuToggle?.addEventListener('click', () => {
  const open = nav.classList.toggle('open');
  menuToggle.setAttribute('aria-expanded', String(open));
  menuToggle.setAttribute('aria-label', open ? 'Close navigation' : 'Open navigation');
});
nav?.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => nav.classList.remove('open')));
window.addEventListener('scroll', () => navbar.classList.toggle('scrolled', window.scrollY > 15), { passive: true });

const projects = {
  career: { category:'FULL-STACK / AI-ASSISTED RESUME SCREENING', title:'Career Portal', description:'A recruitment and resume-screening platform connecting recruiters and candidates through structured workflows and automated document matching.', problem:'Recruiters and candidates need a single place to manage jobs, applications, documents, and interview steps without losing context.', approach:'Built a role-based Django platform with resume and job-description parsers, OCR preprocessing, and TF-IDF/cosine similarity matching.', tech:'Django · SQLite · OpenCV · Tesseract OCR · PyMuPDF · python-docx', features:'Role-based access, job posting, applications, saved jobs, talent pool, interview scheduling, offer letters, onboarding uploads, and candidate rankings.' },
  critix: { category:'FULL-STACK WEB APPLICATION', title:'Critix', description:'A movie review and community platform where users discover movies, write reviews, interact with other users, and manage watchlists.', problem:'Movie communities need more than ratings: they need conversation, discovery, moderation, and a personal way to keep track of what to watch.', approach:'Developed the full-stack product in Django with PostgreSQL and JavaScript, including a custom admin portal and TMDB-powered discovery surfaces.', tech:'Django · PostgreSQL · JavaScript · TMDB API · Vercel · Neon', features:'Movie browsing, filters, ratings, reviews, likes, threaded replies, watchlists, notifications, content reports, moderation, staff access, CSV/Excel import/export, trending and upcoming sections.' },
  toolkit: { category:'COMPUTER VISION / FLASK', title:'Object Detection & Image Processing Toolkit', description:'A browser-based computer vision toolkit providing image-processing operations, video extraction, and detection workflows.', problem:'Computer vision experiments can be difficult to access when every operation requires a separate script or local workflow.', approach:'Created a Flask UI that brings OpenCV operations, frame-by-frame detection, document scanning, and downloadable outputs into one browser experience.', tech:'Flask · OpenCV · Tesseract OCR · ReportLab · Caffe ResNet-10 SSD · Haar cascades', features:'Blur, edge detection, thresholding, morphology, background removal, template matching, blending, video frame extraction, face and eye detection, PDF and text generation.' },
  scanner: { category:'COMPUTER VISION / OCR', title:'Smart Document Scanner', description:'A document workflow that transforms photographed pages into clean scans, extracted text, PDFs, and offline summaries.', problem:'Photographed documents often contain perspective distortion, shadows, noise, and inconsistent layouts that make them hard to read or search.', approach:'Built an automated OpenCV pipeline with document classification, perspective correction, denoising, Tesseract OCR, and a word-frequency extractive summarizer.', tech:'Flask · OpenCV · Tesseract OCR', features:'Document detection, edge detection, perspective correction, shadow removal, denoising, document/poster/invoice classification, OCR, PDF generation, and offline summarization.' },
  csr: { category:'FRONTEND / TEAM PROJECT', title:'Meslova CSR Website', description:'The complete public and admin frontend for a CSR platform, designed around a custom “Premium Luxury” system.', problem:'The CSR platform needed a clear, responsive way to present activity archives, details, galleries, and admin workflows.', approach:'Owned the frontend design and implementation using CSS variables, responsive layouts, sticky navigation, scroll animations, parallax, sliders, and a lightbox.', tech:'HTML · CSS · JavaScript · jQuery · Bootstrap · Django Templates', features:'Public website, admin dashboard, year/category archives, activity details, galleries, add/edit modals, responsive layouts, sticky navigation, parallax, sliders, and lightbox gallery.' },
  handicrafts: { category:'FRONTEND PROJECT', title:'Handicrafts E-Commerce Website', description:'A responsive showcase website for traditional Indian handicrafts.', problem:'Create a clean digital storefront presentation that feels accessible on both desktop and mobile.', approach:'Designed and implemented a responsive interface with a clear visual hierarchy and mobile-conscious layout.', tech:'HTML · CSS · JavaScript', features:'Responsive product showcase, clean layout, accessibility-minded structure, and mobile responsiveness.' },
  nutrition: { category:'FRONTEND PROJECT', title:'Nutrition Diet — Single Serve Packets', description:'A promotional website for nutritious, portable diet packets.', problem:'Communicate product value clearly while keeping the interface friendly and easy to scan.', approach:'Created a focused promotional layout with clear content hierarchy and responsive behavior.', tech:'HTML · CSS · JavaScript', features:'User-friendly UI, content clarity, responsive design, and visual appeal.' },
  currency: { category:'JAVASCRIPT PROJECT', title:'Currency Converter', description:'A dynamic currency conversion interface supporting multiple currencies.', problem:'Make real-time conversion easy to understand with a minimal interaction model.', approach:'Built dynamic input handling and conversion display with a lightweight browser interface.', tech:'JavaScript', features:'Dynamic inputs, multiple currencies, and real-time conversion display.' }
};
const modal = document.getElementById('project-modal');
const closeModal = () => { modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); document.body.style.overflow=''; };
function openProject(key) { const p = projects[key]; if (!p) return; document.getElementById('modal-category').textContent=p.category; document.getElementById('modal-title').textContent=p.title; document.getElementById('modal-description').textContent=p.description; document.getElementById('modal-problem').textContent=p.problem; document.getElementById('modal-approach').textContent=p.approach; document.getElementById('modal-tech').textContent=p.tech; document.getElementById('modal-features').textContent=p.features; modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); document.body.style.overflow='hidden'; document.querySelector('.modal-close').focus(); }
document.querySelectorAll('[data-project]').forEach((button) => button.addEventListener('click', () => openProject(button.dataset.project)));
document.querySelector('.modal-close').addEventListener('click', closeModal);
modal.addEventListener('click', (event) => { if (event.target === modal) closeModal(); });
document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeModal(); });

document.querySelectorAll('.project-filter button').forEach((filter) => filter.addEventListener('click', () => { document.querySelectorAll('.project-filter button').forEach((item) => item.classList.remove('active')); filter.classList.add('active'); const value=filter.dataset.filter; document.querySelectorAll('.project-card').forEach((card) => { card.hidden=value !== 'all' && card.dataset.category !== value; }); }));
const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.style.animationDelay = `${Math.min(entry.target.getBoundingClientRect().top / 1500, .25)}s`; observer.unobserve(entry.target); } }), { threshold: .08 });
document.querySelectorAll('.reveal').forEach((item) => observer.observe(item));
